import img1 from './img/ph.jpg';

export const collection = [
  {
    title: 'Wampirze cesarstwo',
    author: 'Jay Kristoff',
    year: 2021,
    city: 'Warszawa',
    publishingHouse: 'MAG',
    img: img1,
    id: 1,
  },
  {
    title: 'Historia Japonii',
    author: 'Conrad Totman',
    year: 2009,
    city: 'Kraków',
    publishingHouse: 'Uniwersytetu Jagiellońskiego',
    img: img1,
    id: 2,
  },
  {
    title: 'Technologia na start! Botstrap - Tworzenie interfejsów stron WWW',
    author: 'Syed Fazie Rahman',
    year: 2015,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 3,
  },
  {
    title: 'Wstęp fo HTML5 i CSS3 Wyjdź z cienia, opracuj własną stronę WWW!',
    author: 'Bartosz Danowski',
    year: 2011,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 4,
  },
  {
    title: 'CSS nieoficjalny podręcznik Wydanie IV',
    author: 'David Sawyer McFarland',
    year: 2016,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 5,
  },
  {
    title: 'HTNL5 nieoficjalny podręcznik Wydanie II',
    author: 'Matthew NacDanald',
    year: 2014,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 6,
  },
  {
    title: 'Linux Profesjonalne adminiatrowanien systemem Wydanie II',
    author: 'Dennis Matotek, James Turnbull, Peter Lieverdink',
    year: 2018,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 7,
  },
  {
    title: 'Python Instrukcje dla programisty',
    author: 'Eric Matthes',
    year: 2016,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 8,
  },
  {
    title: 'Html5 Tworzenie gier z wykorzystaniem CSS i JAVASCRIPT',
    author: 'Karl Bunyan',
    year: 2016,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 9,
  },
  {
    title: 'AutoCad 2011 PL Pierwsze kroki',
    author: 'Andrzej Pikoń',
    year: 2011,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 10,
  },
  {
    title: 'Node.js w akcji',
    author: 'Mike Cantelon, Marc Harter, Tj Holowaychuk, Nathan Rajlich',
    year: 2015,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 11,
  },
  {
    title: 'Język ANSI C. Programowanie. Wydanie II',
    author: 'Brian W. Kernighan, Dennis M. Ritchie',
    year: 2010,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 12,
  },
  {
    title: 'Rusz głową! Programowanie w JavaScript',
    author: 'Eric Freeman, Elisabeth Robson',
    year: 2015,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 13,
  },
  {
    title:
      'Technologia i zastosowanie mikromechanicznych struktur krzemowych i krzemowo-szklanych w technice mikrosystemów',
    author: 'Jan A. Dziuban',
    year: 2004,
    city: 'Wrocław',
    publishingHouse: 'Oficyna Wydawnicza Politechniki Wroclawskiej',
    img: img1,
    id: 14,
  },
  {
    title: 'Metrologia elektryczna. Wydanie dziewiąte',
    author: 'Augustyn Chwaleba, Maciej Poniński, Andrzej Siedlecki',
    year: 2007,
    city: 'Warszawa',
    publishingHouse: 'Wydawnictwo Naukowo-Trchniczne',
    img: img1,
    id: 15,
  },
  {
    title:
      'Elektryczność i magnetyzm. Zbiór zagadnień i zadań. Część I. Elektrostatyka',
    author: 'Wojciech Michalski',
    year: 2003,
    city: 'Wrocław',
    publishingHouse: 'Oficyna Wydawnicza Politechniki Wroclawskiej',
    img: img1,
    id: 16,
  },
  {
    title: 'Montaż w elektronice',
    author: 'Jan Felba',
    year: 2010,
    city: 'Wrocław',
    publishingHouse: 'Oficyna Wydawnicza Politechniki Wroclawskiej',
    img: img1,
    id: 17,
  },
  {
    title: 'Linux. Komendy i polecenia. Wydanie V',
    author: 'Łukasz Sosna',
    year: 2018,
    city: 'Gliwice',
    publishingHouse: 'Helion',
    img: img1,
    id: 18,
  },
];
